language: r
cache: packages
sudo: required

apt_packages:
 - r-cran-rjags
 - libv8-dev

r_packages:
  - rjags
  - covr

## After success update the code coverage
after_success:
 - Rscript -e 'library(covr);codecov()'
 
## Email notification if the package pass status changes
notifications:
  email:
    recipients:
      - tomaug@ceh.ac.uk
    on_success: change
    on_failure: change

# Warnings dont fail build
warnings_are_errors: false

## Set up the matrix of different runs
env:
  matrix:
    - r: release
      not_cran: true
      R_BUILD_ARGS:"--no-build-vignettes --no-manual --no-resave-data"
      R_CHECK_ARGS:"--no-manual --no-build-vignettes"
    - r: release
      not_cran: false
      R_BUILD_ARGS:"--no-build-vignettes --no-manual --no-resave-data"
      R_CHECK_ARGS:"--no-manual --no-build-vignettes --as--cran"
    - r: devel
      not_cran: true
      R_BUILD_ARGS:"--no-build-vignettes --no-manual --no-resave-data"
      R_CHECK_ARGS:"--no-manual --no-build-vignettes"
    - r: devel
      not_cran: false
      R_BUILD_ARGS:"--no-build-vignettes --no-manual --no-resave-data"
      R_CHECK_ARGS:"--no-manual --no-build-vignettes --as--cran"